version: 3
jobs:
  teststyle:
    docker:
      - image: ubuntu:artful
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: apt-get update -y && apt-get install git clang-format-5.0 -y
      - run:
          name: Style checker
          command: bash scripts/stylecheck.sh
  build:
    docker:
      - image: ubuntu:artful
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: apt-get update -y && apt-get install libyaml-cpp-dev libsqlite3-dev util-linux librsvg2-dev libcairomm-1.0-dev libepoxy-dev libgtkmm-3.0-dev uuid-dev libboost-dev  libzmq5 libzmq3-dev libglm-dev libgit2-dev libcurl4-gnutls-dev liboce-ocaf-dev cmake -y
      - run:
          name: Build
          command: ./compile.sh

workflows:
  version: 2
  test-and-build:
    jobs:
      - teststyle
      - build:
          requires:
            - teststyle
